apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poctestpvc
  namespace: testing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: ceph