apiVersion: v1
kind: Pod
metadata:
  name: csi-migration-toolpod
  namespace: testing
spec:
  containers:
  - args:
    - -c
    - while true; do echo hello; sleep 10;done
    command:
    - /bin/sh
    env:
    - name: pathmapper
      value: '{"/mnt/old/0": "/data/db"}'
    - name: mountpaths
      value: '[{"mountPath": "/data/db", "name": "mongo-pvc-test"}]'
    image: lockat/toolpod:v17
    name: toolpod
    volumeMounts:
    - mountPath: /data/db
      name: mongo-pvc-test-csi
    - mountPath: /mnt/old/0
      name: mongo-pvc-test
  restartPolicy: Never
  volumes:
  - name: mongo-pvc-test
    persistentVolumeClaim:
      claimName: mongo-pvc-test
  - name: mongo-pvc-test-csi
    persistentVolumeClaim:
      claimName: mongo-pvc-test-csi
