apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-test
  namespace: testing
  labels:
    app: test-mongo1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: ceph